// canciones.js
const listaCancionesBase = [
    { t: "September", a: "Earth, Wind & Fire", y: 1978, idYT: "Gs069dndIYk" },
    { t: "Take On Me", a: "a-ha", y: 1984, idYT: "djV11Xbc914" },
    { t: "Beat It", a: "Michael Jackson", y: 1982, idYT: "oRdxUFDoQe0" },
    { t: "Toxic", a: "Britney Spears", y: 2003, idYT: "LOZuxwVk7TU" },
    { t: "Uptown Funk", a: "Bruno Mars", y: 2014, idYT: "OPf0YbXqDm0" },
    { t: "Rayando El Sol", a: "Maná", y: 1990, idYT: "tcWzVUlR7Y4" },
    { t: "Gasolina", a: "Daddy Yankee", y: 2004, idYT: "qGKrc3Vz12g" },
    { t: "Stayin Alive", a: "Bee Gees", y: 1977, idYT: "I_izvAbhExY" },
    { t: "Fortnight", a: "Taylor Swift ft. Post Malone", y: 2024, idYT: "q3zqJs7JUCQ" },
    { t: "Espresso", a: "Sabrina Carpenter", y: 2024, idYT: "eVli-tstM5E" },
    { t: "Not Like Us", a: "Kendrick Lamar", y: 2024, idYT: "H58vbez_m4E" },
    { t: "Houdini", a: "Eminem", y: 2024, idYT: "22tVWwmTie8" },
    { t: "Flowers", a: "Miley Cyrus", y: 2023, idYT: "G7KNmW9a75Y" },
    { t: "Vampire", a: "Olivia Rodrigo", y: 2023, idYT: "RlPNh_PB6W8" },
    { t: "As It Was", a: "Harry Styles", y: 2022, idYT: "H5v3kku4y6Q" },
    { t: "Blinding Lights", a: "The Weeknd", y: 2019, idYT: "4NRXx6tfk8Q" },
    { t: "Levitating", a: "Dua Lipa", y: 2020, idYT: "TUVcZfQe-Kw" },
    { t: "Shape of You", a: "Ed Sheeran", y: 2017, idYT: "JGwWNGJdvx8" },
    { t: "Starboy", a: "The Weeknd", y: 2016, idYT: "34Na4j8AVgA" },
    { t: "Uptown Funk", a: "Mark Ronson ft. Bruno Mars", y: 2014, idYT: "OPf0YbXqDm0" },
    { t: "Get Lucky", a: "Daft Punk", y: 2013, idYT: "5NV6Rdv1a3I" },
    { t: "Rolling in the Deep", a: "Adele", y: 2010, idYT: "rYEDA3JcQqw" },
    { t: "Bad Romance", a: "Lady Gaga", y: 2009, idYT: "qrO4VZDFvnU" },
    { t: "Viva La Vida", a: "Coldplay", y: 2008, idYT: "dvgZkm1xWPE" },
    { t: "Umbrella", a: "Rihanna", y: 2007, idYT: "CvBfHwUxHIk" },
    { t: "Hips Don't Lie", a: "Shakira", y: 2005, idYT: "DUT5rEU6pqM" },
    { t: "Mr. Brightside", a: "The Killers", y: 2004, idYT: "gGdGFtwCNBE" },
    { t: "Seven Nation Army", a: "The White Stripes", y: 2003, idYT: "0J2QdDbelmY" },
    { t: "Lose Yourself", a: "Eminem", y: 2002, idYT: "_Yhyp-_hX2s" },
    { t: "In the End", a: "Linkin Park", y: 2000, idYT: "eVTXPUF4Oz4" },
    { t: "Smooth", a: "Santana ft. Rob Thomas", y: 1999, idYT: "6Whgn_iE5uc" },
    { t: "Believe", a: "Cher", y: 1998, idYT: "nZRLVpOkWCI" },
    { t: "Wannabe", a: "Spice Girls", y: 1996, idYT: "gJLIiF15wjQ" },
    { t: "Wonderwall", a: "Oasis", y: 1995, idYT: "6hzrDeceEKc" },
    { t: "Zombie", a: "The Cranberries", y: 1994, idYT: "6Ejga4kJUts" },
    { t: "Creep", a: "Radiohead", y: 1992, idYT: "XFkzRNyygfk" },
    { t: "Smells Like Teen Spirit", a: "Nirvana", y: 1991, idYT: "hTWKbfoikeg" },
    { t: "Losing My Religion", a: "R.E.M.", y: 1991, idYT: "xwtdhWljSIg" },
    { t: "Thunderstruck", a: "AC/DC", y: 1990, idYT: "v2AC41dglnM" },
    { t: "Billie Jean", a: "Michael Jackson", y: 1982, idYT: "Zi_XLOBDo_Y" },
    { t: "Under Pressure", a: "Queen & David Bowie", y: 1981, idYT: "a01QQZyl-_I" },
    { t: "Don't Stop Believin'", a: "Journey", y: 1981, idYT: "1k8dqizhmko" },
    { t: "Another One Bites the Dust", a: "Queen", y: 1980, idYT: "rY0WxgSXdEE" },
    { t: "Stayin' Alive", a: "Bee Gees", y: 1977, idYT: "fNFzfwO79Hk" },
    { t: "Dreams", a: "Fleetwood Mac", y: 1977, idYT: "Y3ywicffOj4" },
    { t: "Bohemian Rhapsody", a: "Queen", y: 1975, idYT: "fJ9rUzIMcZQ" },
    { t: "Hotel California", a: "Eagles", y: 1976, idYT: "EqPtz5qN7HM" },
    { t: "Imagine", a: "John Lennon", y: 1971, idYT: "YkgkThdzX-8" },
    { t: "Let It Be", a: "The Beatles", y: 1970, idYT: "QDYfEBY9nmU" },
    { t: "Fortunate Son", a: "Creedence Clearwater Revival", y: 1969, idYT: "ZWijx_AgPi8" },
    { t: "Hey Jude", a: "The Beatles", y: 1968, idYT: "A_MjCqQoLLA" },
    { t: "Respect", a: "Aretha Franklin", y: 1967, idYT: "6FOUqQt3Kg0" },
    { t: "Paint It, Black", a: "The Rolling Stones", y: 1966, idYT: "O4irXQhgMqg" },
    { t: "Yesterday", a: "The Beatles", y: 1965, idYT: "jo505ZyaCbA" },
    { t: "Oh, Pretty Woman", a: "Roy Orbison", y: 1964, idYT: "lnRS3A_iIYg" },
    { t: "Stand by Me", a: "Ben E. King", y: 1961, idYT: "hwZNL7QVJjE" },
    { t: "Johnny B. Goode", a: "Chuck Berry", y: 1958, idYT: "T38vBIme50E" },
    { t: "Jailhouse Rock", a: "Elvis Presley", y: 1957, idYT: "gj0Rz-uP4Mk" }, // Agregada coma aquí
    { t: "El Rey", a: "Vicente Fernández", y: 1971, idYT: "M6T91L6Yp_c" },
    { t: "Amorcito Corazón", a: "Pedro Infante", y: 1949, idYT: "6_pM-7P6Y88" },
    { t: "Bésame Mucho", a: "Consuelo Velázquez", y: 1940, idYT: "kIDW6QAE-m4" },
    { t: "Cielito Lindo", a: "Quirino Mendoza y Cortés", y: 1882, idYT: "XunpS6G_K04" },
    { t: "La Llorona", a: "Chavela Vargas", y: 1961, idYT: "V9m8o99_p94" },
    { t: "Cien Años", a: "Pedro Infante", y: 1953, idYT: "v8_3W_V-NIs" },
    { t: "Si Nos Dejan", a: "José Alfredo Jiménez", y: 1961, idYT: "Fp2UjBshf-M" },
    { t: "Sabor a Mí", a: "Álvaro Carrillo", y: 1959, idYT: "0X4Bv_U0tI0" },
    { t: "La Bamba", a: "Ritchie Valens", y: 1958, idYT: "jSKJQ18ZoIA" },
    { t: "Paloma Negra", a: "Lola Beltrán", y: 1954, idYT: "f8jV6I07C9k" },
    { t: "El Jinete", a: "José Alfredo Jiménez", y: 1953, idYT: "fR4C_07YmOQ" },
    { t: "México Lindo y Querido", a: "Jorge Negrete", y: 1945, idYT: "Gf92-p_B87E" },
    { t: "La Nave del Olvido", a: "José José", y: 1970, idYT: "Lg23L6u8pL0" },
    { t: "El Triste", a: "José José", y: 1970, idYT: "E20G25SssS4" },
    { t: "Querida", a: "Juan Gabriel", y: 1984, idYT: "oADT7f766P0" },
    { t: "Amor Eterno", a: "Juan Gabriel", y: 1984, idYT: "0_L6O9I9iI0" },
    { t: "La Media Vuelta", a: "José Alfredo Jiménez", y: 1963, idYT: "m6E6A21S_N8" },
    { t: "Tristes Recuerdos", a: "Antonio Aguilar", y: 1982, idYT: "6fG9O7i2L1E" },
    { t: "Por Tu Maldito Amor", a: "Vicente Fernández", y: 1989, idYT: "Z7U68Y05WzM" },
    { t: "Como la Flor", a: "Selena", y: 1992, idYT: "F99XfA7M8G4" },
    { t: "La Incondicional", a: "Luis Miguel", y: 1988, idYT: "5v6I9W_vL8Q" },
    { t: "Culpable o No", a: "Luis Miguel", y: 1988, idYT: "8I0B5k7A7jU" },
    { t: "Rayando el Sol", a: "Maná", y: 1990, idYT: "Y4E0U8v8Z9Q" },
    { t: "Pachuco", a: "Maldita Vecindad", y: 1991, idYT: "N0mS_G6Qx0k" },
    { t: "Afuera", a: "Caifanes", y: 1994, idYT: "H58W6zGv_9M" },
    { t: "Ingrata", a: "Café Tacvba", y: 1994, idYT: "fM52m6W-pZ8" },
    { t: "Gimme Tha Power", a: "Molotov", y: 1997, idYT: "6wF5W0S8O-w" },
    { t: "Kumbala", a: "Maldita Vecindad", y: 1991, idYT: "m9N66B0W_sQ" },
    { t: "Eres", a: "Café Tacvba", y: 2003, idYT: "98Akpf1ph2o" },
    { t: "No Rompas Más", a: "Caballo Dorado", y: 1997, idYT: "Gf0yV8_0L6E" },
    { t: "La Boa", a: "La Sonora Santanera", y: 1960, idYT: "wY8Z9X0_B_M" },
    { t: "Perfume de Gardenias", a: "La Sonora Santanera", y: 1960, idYT: "G5yU9wI2L-w" },
    { t: "Que Nadie Sepa Mi Sentir", a: "La Sonora Dinamita", y: 1981, idYT: "f5G_L8O9wU0" },
    { t: "El Sirenito", a: "Rigo Tovar", y: 1978, idYT: "F8U9X6_vL0E" },
    { t: "Cómo Te Voy a Olvidar", a: "Los Ángeles Azules", y: 1996, idYT: "h5V8w9L0z_M" },
    { t: "17 Años", a: "Los Ángeles Azules", y: 1999, idYT: "wV9z_X0_B5M" },
    { t: "Oye Mi Amor", a: "Maná", y: 1992, idYT: "F5U8z9X0_L6" },
    { t: "Viento", a: "Caifanes", y: 1988, idYT: "gG9z_W0_v5M" },
    { t: "Cerca de Ti", a: "Lucerito", y: 1982, idYT: "h5V8X0_z6LM" },
    { t: "Mírame", a: "Timbiriche", y: 1987, idYT: "F5U9X0_v6LM" },
    { t: "Besos de Ceniza", a: "Timbiriche", y: 1987, idYT: "hG9z_W0_L5M" },
    { t: "Tú y Yo", a: "Thalía", y: 1990, idYT: "g5U8X0_v6LM" },
    { t: "Media Naranja", a: "Fey", y: 1995, idYT: "hG9X0_z6vLM" },
    { t: "Muriendo Lento", a: "Timbiriche", y: 1993, idYT: "F5U8z_W0L6M" },
    { t: "Azúcar Amargo", a: "Fey", y: 1996, idYT: "h5V9z_X0B6M" },
    { t: "Provócame", a: "Chayanne", y: 1992, idYT: "gG9X0_v5L6M" },
    { t: "Sopa de Caracol", a: "Banda Blanca", y: 1991, idYT: "h5U8z_W0v6M" },
    { t: "Claridad", a: "Menudo", y: 1981, idYT: "F5V9z_X0L6M" },
    { t: "Súbete a Mi Moto", a: "Menudo", y: 1981, idYT: "hG9X0_v6L5M" },
    { t: "La Macarena", a: "Los del Río", y: 1993, idYT: "g5V8z_W0B6M" }
];